# Generated by Django 2.1.7 on 2019-02-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='restaurant',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='description',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
    ]
